# Generated by Django 4.2.3 on 2023-07-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_user_id', models.CharField(max_length=50)),
                ('spotify_user_locale', models.CharField(max_length=50)),
                ('playlist_id', models.CharField(max_length=50)),
                ('uploaded_files_count', models.IntegerField()),
                ('failed_files_count', models.IntegerField()),
                ('succeeded_files_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
